export const SHEET_TABS = {
  USUARIOS: "Usuarios",
  AREAS: "Areas",
  ESPACIOS: "Espacios",
  MAPAS: "Mapas",
  RECURSOS: "Recursos",
  RECURSO_ESPACIO: "RecursoEspacio",
  RESERVAS: "Reservas",
  RESERVA_RECURSOS: "ReservaRecursos",
  EVENTO_HISTORICO: "EventoHistorico",
  NOTIFICACIONES: "Notificaciones",
} as const;

export type SheetTab = (typeof SHEET_TABS)[keyof typeof SHEET_TABS];

export const SHEET_HEADERS: Record<SheetTab, string[]> = {
  Usuarios: [
    "id",
    "email",
    "username",
    "passwordHash",
    "role",
    "areaId",
    "active",
    "receiveApprovalEmails",
  ],
  Areas: ["id", "name", "code"],
  Espacios: [
    "id",
    "name",
    "floor",
    "capacity",
    "geometryJson",
    "mapId",
    "active",
    /** Al final para no desalinear filas existentes (antes de minCapacity). */
    "minCapacity",
  ],
  Mapas: ["id", "name", "backgroundType", "backgroundUrl", "width", "height"],
  Recursos: [
    "id",
    "name",
    "type",
    "totalQty",
    "imageUrl",
    "scope",
    "active",
  ],
  RecursoEspacio: ["resourceId", "spaceId"],
  Reservas: [
    "id",
    "eventName",
    "spaceIds",
    "areaId",
    "userId",
    "startAt",
    "endAt",
    "recurrenceRule",
    "status",
    "eventDescription",
    "pendingAction",
    "pendingPayload",
    "approvalToken",
    "estimatedAttendees",
    "attendeeJustificationCode",
    "attendeeJustificationNote",
    "actualAttendees",
    "attendanceComment",
  ],
  ReservaRecursos: ["reservationId", "resourceId", "quantity"],
  EventoHistorico: ["eventName", "areaId", "count", "lastUsedAt"],
  Notificaciones: [
    "id",
    "userId",
    "areaId",
    "reservationId",
    "type",
    "message",
    "read",
    "createdAt",
  ],
};
